### ISSUE TITLE
AttributeError: 'JPEG' object has no attribute 'decompressor'

### ISSUE THREAD

**Issue by vikalpjain91** [bamps53/kaggle-autonomous-driving2019#2]
While executing your code we got this issue:
    jpeg.JPEG("D:\Work\ML\API\MNB\28 - AUTONOMOUS VEHICLE-KAGGLE\Winners_solution\Try\1.jpeg")
  File "D:\Installation\Anaconda\lib\site-packages\jpeg4py\_py.py", line 128, in __init__
    super(JPEG, self).__init__(lib_)
  File "D:\Installation\Anaconda\lib\site-packages\jpeg4py\_py.py", line 64, in __init__
    jpeg.initialize()
  File "D:\Installation\Anaconda\lib\site-packages\jpeg4py\_cffi.py", line 212, in initialize
    _initialize(backends)
  File "D:\Installation\Anaconda\lib\site-packages\jpeg4py\_cffi.py", line 193, in _initialize
    raise OSError("Could not load libjpeg-turbo library")
OSError: Could not load libjpeg-turbo library
Exception ignored in: <function JPEG.__del__ at 0x000002A7FB446438>
Traceback (most recent call last):
  File "D:\Installation\Anaconda\lib\site-packages\jpeg4py\_py.py", line 215, in __del__
    if self.decompressor is not None:
AttributeError: 'JPEG' object has no attribute 'decompressor'

I have installed jpeg4py using pip but not sure from where I can get rid of this issue.
Any work around? I am currently using windows and Linux I dont have access as of now.

Reference where you have used JPEG():
https://github.com/bamps53/kaggle-autonomous-driving2019/blob/master/datasets/dataset_factory.py
Line: 44

**Comment by vikalpjain91** [comment]
is cv2.imread(image_path, cv2.IMREAD_UNCHANGED)

will be fine?
